- name: create secret
  uri:
    url: "{{vault_address}}/v1/{{secret_kv_path}}/data/{{item.secret_name}}"
    method: POST
    body_format: json
    headers:
      X-Vault-Token: "{{vault_session_token}}"
    body:
      data: "{{item.secret_contents}}"
  when: item.update_vault_secret
